### ISSUE TITLE
[CSS FIX] mobile screen navbar

### ISSUE THREAD

**Issue by nikhilpawar9** [ITESA-DYPCOE/ITESA_WEBSITE#15]
*Describe the bug*
on mobile viewport < 580px, fix navbar item css

Pls refer follow snapshot for the issue

![WhatsApp Image 2021-09-30 at 12 48 14 PM](https://user-images.githubusercontent.com/59965072/135405785-08365797-9f32-489e-9e24-04370618aeb3.jpeg)

**Comment by ShubhamSj07** [comment]
@nikhilpawar9 , i would like to fix this

**Comment by ShubhamSj07** [comment]
I have fixed this issue
