### ISSUE TITLE
Past events alignment in Admin

### ISSUE THREAD

**Issue by AmeyaJain-25** [ITESA-DYPCOE/ITESA_WEBSITE#18]
**Describe the bug**
The past events rows are not aligned properly. Screenshot given below

**Expected behavior**
All should be aligned one below the other

**Screenshots**
![image](https://user-images.githubusercontent.com/66305085/135437952-ffcf3a55-37fa-4646-a3c0-450b29a1fd3e.png)

**Additional context**
Please assign me this issue

**Comment by ShubhamSj07** [comment]
@AmeyaJain-25, go ahead🤘🚀
